/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnglamorousRouteImport } from './routes/unglamorous'
import { Route as PlantedtankRouteImport } from './routes/plantedtank'
import { Route as EcologyRouteImport } from './routes/ecology'
import { Route as IndexRouteImport } from './routes/index'

const UnglamorousRoute = UnglamorousRouteImport.update({
  id: '/unglamorous',
  path: '/unglamorous',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantedtankRoute = PlantedtankRouteImport.update({
  id: '/plantedtank',
  path: '/plantedtank',
  getParentRoute: () => rootRouteImport,
} as any)
const EcologyRoute = EcologyRouteImport.update({
  id: '/ecology',
  path: '/ecology',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ecology': typeof EcologyRoute
  '/plantedtank': typeof PlantedtankRoute
  '/unglamorous': typeof UnglamorousRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ecology': typeof EcologyRoute
  '/plantedtank': typeof PlantedtankRoute
  '/unglamorous': typeof UnglamorousRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ecology': typeof EcologyRoute
  '/plantedtank': typeof PlantedtankRoute
  '/unglamorous': typeof UnglamorousRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ecology' | '/plantedtank' | '/unglamorous'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ecology' | '/plantedtank' | '/unglamorous'
  id: '__root__' | '/' | '/ecology' | '/plantedtank' | '/unglamorous'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EcologyRoute: typeof EcologyRoute
  PlantedtankRoute: typeof PlantedtankRoute
  UnglamorousRoute: typeof UnglamorousRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unglamorous': {
      id: '/unglamorous'
      path: '/unglamorous'
      fullPath: '/unglamorous'
      preLoaderRoute: typeof UnglamorousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plantedtank': {
      id: '/plantedtank'
      path: '/plantedtank'
      fullPath: '/plantedtank'
      preLoaderRoute: typeof PlantedtankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecology': {
      id: '/ecology'
      path: '/ecology'
      fullPath: '/ecology'
      preLoaderRoute: typeof EcologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EcologyRoute: EcologyRoute,
  PlantedtankRoute: PlantedtankRoute,
  UnglamorousRoute: UnglamorousRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
